#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [ ! -d .venv ]; then
  python -m venv .venv
fi

# shellcheck disable=SC1091
source .venv/bin/activate

python -m pip install --upgrade pip || true
python -m pip install --no-build-isolation -e .

mkdir -p .codespaces
cat > .codespaces/agent-env <<'ENVEOF'
# Generated by scripts/codespaces-startup.sh
export PYTHONPATH=src
export EMAIL_AGENT_CONTACT_STORE=contacts.json
ENVEOF

echo "Codespaces startup complete."
echo "Use: source .codespaces/agent-env && source .venv/bin/activate"
